version: "3.2"
services:
  back:
    image: back.image:latest
    build: ./
    ports:
    - 80:5000
    expose:
    - "80"
    restart: always
    environment:
        NODE_ENV: production
        PORT: 5000
        HOST: 0.0.0.0
